"""
Ingest Brady Defibaugh (April 2026) Syriac pharmaceutical decipherment hypotheses.

Source: raw/research/A Syriac Pharmaceutical Dispensatory Encoded in the Voynich
Manuscript- Statistical and Philological Evidence from Consonant Skeleton Analysis.pdf

Creates H-BRADY-01 through H-BRADY-14 in hypotheses/.
"""
import json
from datetime import date
from pathlib import Path

HYP_DIR = Path(r"C:\Projects\brain-v\hypotheses")
SRC = "Brady Defibaugh (April 2026), A Syriac Pharmaceutical Dispensatory Encoded in the Voynich Manuscript (DANI pipeline v31)"

def h(idx, claim, typ, conf, evidence_for, evidence_against, test, metric, threshold,
      reasoning):
    return {
        "id": f"H-BRADY-{idx:02d}",
        "claim": claim,
        "type": typ,
        "confidence": conf,
        "evidence_for": evidence_for,
        "evidence_against": evidence_against,
        "test": test,
        "test_metric": metric,
        "test_threshold": threshold,
        "tests_run": [],
        "tests_remaining": [test],
        "status": "active",
        "parent": None,
        "created": str(date.today()),
        "last_tested": None,
        "reasoning": reasoning,
        "source": SRC,
        "researcher": "brady-defibaugh",
    }

HYPS = [
    h(1,
      "The Voynich Manuscript encodes an Aramaic pharmaceutical text in the Syriac tradition, using a consonant-skeleton abjad with stripped vowels, matching 86.9% of 35,259 filtered tokens against a 1,334-entry Syriac pharmaceutical lexicon.",
      "language", 0.40,
      ["87.0% token coverage at z=3.83 vs 500 random permutations (p<0.001)",
       "Syriac (85.1%) nearly doubles Hebrew (47.9%) and Arabic (48.0%) coverage",
       "Cross-domain confirmation: 14 plant-image/text matches at Fisher p=6.66e-16"],
      ["Author own confidence for Syriac-specifically is 40-50%",
       "Short-skeleton ambiguity: 42.9% of tokens have only 1-2 consonant skeletons",
       "No connected Syriac prose has been read by a specialist",
       "Permutation baseline mean 71.5% is itself high — suggests lexicon may be over-permissive"],
      "Reproduce DANI mapping + permutation test independently; verify z-score and language-discrimination gap",
      "dani_coverage_z_score",
      ">=3.0 and Syriac > Hebrew+Arabic by >=15pp: support. z<2.0: rejection.",
      "Flagship claim of the paper. Requires independent implementation to verify."),

    h(2,
      "Plain gallows characters EVA 't' and 'p' are non-phonetic paragraph/section markers, not consonants: 'p' shows 5.4x line-initial enrichment (70.9% vs 13.1% baseline), 't' shows 3.2x (42.3%), while bench gallows (cth/ckh/cph) appear in normal mid-word positions.",
      "structural", 0.70,
      ["Direct positional statistics computable from corpus",
       "Stripping plain gallows as prefixes recovers 4.3pp coverage in Brady's pipeline",
       "Consistent with other researchers who've noted gallows positional anomalies"],
      ["No known paleographic analogue for mid-word phonetic vs. line-initial marker distinction within a single script"],
      "Compute line-initial frequency of EVA 't','p','cth','ckh','cph' against 13.1% baseline",
      "gallows_line_initial_enrichment",
      "'p' >=4.0x and 't' >=2.5x, bench gallows <1.5x: confirmed. Otherwise: challenged.",
      "Testable today from existing corpus. Independent of Syriac hypothesis."),

    h(3,
      "EVA 'q' maps to Syriac waw, producing the conjunction wa- ('and') at 14.9% of tokens — a frequency consistent with attested Syriac prose.",
      "cipher", 0.35,
      ["14.9% matches published Syriac prose wa- frequency",
       "q is known to be heavily position-constrained in Voynichese (initial only)"],
      ["q initial frequency could match many high-frequency features; single-datapoint match",
       "No independent test beyond self-consistency with hypothesis"],
      "Measure: what fraction of tokens begin with EVA 'q'? Compare to 14.9% prediction",
      "q_initial_fraction",
      "Within [12%,18%]: support. Outside: challenged.",
      "Simple to verify from corpus."),

    h(4,
      "The encoding drops pharyngeal consonants (Syriac het and ayin have no EVA representation) — consistent with a non-Semitic (European) copyist who lacks these phonemes.",
      "cipher", 0.40,
      ["Lexicon 'yn'=aynā ('eye', 699 tokens) matches without the initial ayin",
       "Pharmaceutical vocabulary with het (kuhla, mashha, hamra) initially invisible without this assumption"],
      ["Dropping phonemes creates systematic homograph ambiguity (e.g., 'kl' = kol/kuhla/kalla)",
       "Convenient assumption that rescues otherwise unmatched vocabulary"],
      "Test whether reintroducing het/ayin assumptions changes coverage significantly; count homograph collisions produced",
      "pharyngeal_drop_plausibility",
      "Structural argument more than numerical test. Evaluate qualitatively.",
      "Linguistic plausibility claim; numerical test secondary."),

    h(5,
      "EVA vowel characters (a,o,e,i), currently stripped by the consonant-skeleton pipeline, encode real phonetic distinctions in Syriac vowels: EVA 'e'→ī, EVA 'o'→o/u, EVA 'a'→a/ā. Disambiguation layer resolves 7,007 tokens (20% of corpus) at >=70% confidence.",
      "cipher", 0.35,
      ["Skeleton 'kl' (1,059 tokens) splits into three populations via vowel pattern",
       "130 tokens of _o_a_ pattern (e.g. 'okal') read as kuhla ('collyrium') on pharma pages",
       "'chedy' vs 'chody' (same skeleton kdy) show sectional difference scores 78-110"],
      ["Vowel-pattern assignment may be circular: is kuhla concentrated on pharma pages because of the encoding rule, or fit to that distribution?",
       "Independent test requires separate vowel-disambiguation implementation"],
      "Independent: partition 'chedy' vs 'chody' tokens by section; chi-square test for non-random distribution",
      "vowel_sectional_chi_square",
      "chi-square p<0.001: confirmed vowels carry info. p>0.05: refuted.",
      "Partially testable now; full test requires vowel-layer implementation."),

    h(6,
      "The Voynich text uses the Sergian translation tradition (6th century Syriac), evidenced by: (a) tak-sa for dynamis (not haylā), (b) <=8 Greek loanwords (40 tokens total, all short transliterations), (c) native Syriac plant names dominate.",
      "language", 0.30,
      ["Near-total absence of long Greek transliterations in decoded output",
       "Matches Calà and Hawley 2017 'translated' subset (270/477 Sergius entries)"],
      ["Absence of Greek is also consistent with text not being Syriac at all",
       "Dating the cipher to 6th-century tradition when the MS is 15th-century requires source-copy hypothesis"],
      "Count Greek-transliteration-compatible skeletons in decoded output; compare against Sergian baseline",
      "greek_loanword_count",
      "<=10 distinct Greek terms and <=60 tokens: consistent. >20 terms: challenged.",
      "Dating/tradition claim; hinges on primary hypothesis."),

    h(7,
      "The Syriac temporal adverb kaddīn (skeleton kdy) appears 1,326 times (3.8% of corpus) while the Jewish Babylonian Aramaic equivalent kəḏēn (skeleton kdn) appears 178 times — an 88:12 ratio supporting primarily Syriac text with minor JBA influence.",
      "language", 0.35,
      ["Direct skeleton-level claim, testable from corpus",
       "1,326 tokens is a large, statistically stable count",
       "kdy and kdn are distinguishable skeletons"],
      ["3.8% is unusually high for a temporal adverb — may indicate non-linguistic function",
       "Could also be some other Semitic word with same skeleton"],
      "Count skeleton tokens 'kdy' (chedy/chody/ckhedy etc. by char map) and 'kdn' in corpus",
      "kdy_kdn_ratio",
      "kdy:kdn >=4:1 AND kdy >=3% of corpus: confirmed. Otherwise: challenged.",
      "Directly testable with character mapping."),

    h(8,
      "Syriac āsyā ('physician') dominates JBA rappā 37:1, confirming primarily Syriac rather than JBA tradition.",
      "language", 0.30,
      ["Small absolute counts but large ratio",
       "Pharmaceutical text should contain physician vocabulary"],
      ["Absolute count of rappā (1) is below statistical significance threshold",
       "37:1 is fragile to single-token misidentification"],
      "Count skeletons '>sy' and 'rp' in corpus; verify 37:1 directivity",
      "asya_rappa_ratio",
      "Ratio >=10:1: confirmed direction. <3:1: refuted.",
      "Fragile ratio but directly testable."),

    h(9,
      "Herbal pages describe Galenic pharmaceutical properties (kyānā 'nature', ṭārā 'press/apply') rather than botanical catalogs — adding Löw botanical entries (42 terms) increased herbal coverage by only 0.1pp, and top decoded words match pharma page vocabulary.",
      "structural", 0.35,
      ["0.1pp coverage change from 42-term botanical supplement is low ceiling",
       "kyānā enriched 3.3x on herbal pages, ṭārā 3.2x — suggests pharma vocabulary"],
      ["Top-word overlap could also reflect shared function-word vocabulary",
       "The 0.1pp test is contingent on lexicon completeness"],
      "Compare decoded top-10 words on herbal vs pharma folios for overlap percentage",
      "herbal_pharma_vocab_overlap",
      ">=70% top-10 overlap: confirmed. <30%: refuted.",
      "Requires Brady pipeline output to fully test."),

    h(10,
      "78.7% of herbal folios have a unique skeleton in position B (word immediately following a gallows marker), with lower lexicon match rates (52.6% vs 65.8%) and higher hapax (76.6% vs 67.8%) — consistent with plant-name headings behind gallows.",
      "structural", 0.45,
      ["Two-way difference (lower match AND higher hapax) harder to fake",
       "Plant names are a natural place for unique vocabulary",
       "Structural claim independent of lexicon quality"],
      ["Position-B effects could also reflect scribal line-beginning conventions"],
      "Measure hapax rate and lexicon match rate at position B vs baseline across herbal folios",
      "position_b_hapax_gap",
      "position-B hapax >= baseline+5pp AND match rate <= baseline-5pp: confirmed.",
      "Computable from corpus + lexicon. High-value test."),

    h(11,
      "Nine Syriac pharmaceutical phrase-structure templates (TREATMENT, RECIPE_ACTION, etc.) match 109 decoded passages across all 225 folios, clustered on pharma and biological pages (f75v, f84r, f102r2, f102v2, f107r).",
      "structural", 0.25,
      ["109 matches across 225 folios is not random",
       "Templates derived from independent primary sources (Bhayro, Budge, Müller-Kessler)"],
      ["109 matches / 225 folios ≈ 0.48/folio — is this above chance?",
       "Template flexibility not specified; could be over-permissive",
       "Brady has not published null-distribution comparison for templates"],
      "Replicate template matching with same 9 templates against shuffled-word baseline; compute z-score",
      "phrase_template_z_score",
      "z>=3.0 vs shuffle: confirmed. z<2.0: refuted.",
      "Strong test — if templates fire on shuffled corpus, whole grammar claim collapses."),

    h(12,
      "Short skeletons (1-2 consonants) cover 42.9% of corpus tokens and are irreducibly ambiguous, meaning ANY decipherment hypothesis using consonant-skeleton methodology has ceiling ~57% on word-level accuracy without a vowel-disambiguation layer.",
      "structural", 0.70,
      ["Mathematical consequence of skeleton length distribution",
       "Independent of which Semitic language is assumed",
       "Brady acknowledges this as a primary limitation"],
      ["Short-skeleton ambiguity could be partially resolved by contextual co-occurrence"],
      "Compute length distribution of Brady-map skeletons; fraction with length <=2",
      "short_skeleton_fraction",
      "42.9% +/- 2pp: confirmed.",
      "Almost trivially testable. Critical for bounding all Syriac claims."),

    h(13,
      "The random-permutation baseline of 71.5% coverage is anomalously high — random permutations of 10 consonants against a 1,334-entry lexicon should not match >70% of arbitrary token streams. This suggests the lexicon is over-permissive and the 15.4pp gap to true mapping is smaller than typical for a genuine signal.",
      "null", 0.45,
      ["71.5% random baseline is unusually high by cryptanalytic norms",
       "A 1,334-entry lexicon over a 10-consonant alphabet has ~10^10 possible skeletons — yet random permutations achieve 71%"],
      ["High baseline could legitimately reflect dense Syriac lexicon and short-skeleton collisions",
       "z=3.83 still exceeds p<0.001 threshold"],
      "Reproduce permutation test with different lexicon sizes to see if baseline tracks lexicon density",
      "baseline_lexicon_density",
      "Random baseline scales >80% with lexicon size alone: lexicon is over-permissive.",
      "Key skeptical test. If baseline rises with lexicon regardless of content, z-score is inflated."),

    h(14,
      "The encoding reflects a 15th-century European scribe transcribing a Syriac pharmaceutical source: kaph/qoph merger (velar/uvular confusion), pharyngeal drop (het/ayin absent), gallows as paragraph markers — all consistent with a non-Semitic copyist using a purpose-built script.",
      "structural", 0.30,
      ["Author profile aligns with radiocarbon date (1404-1438) and north Italian provenance",
       "Jewish physicians working with Syriac sources in 15th-century Italy is historically documented",
       "Multiple independent structural features converge on one copyist profile"],
      ["Copyist hypothesis is unfalsifiable in its general form",
       "Each structural feature in isolation has other possible explanations"],
      "Qualitative historical plausibility check; no direct statistical test",
      "copyist_profile_coherence",
      "Narrative coherence evaluation only.",
      "Synthetic claim combining H-BRADY-02, 03, 04. Evaluate last."),
]

for hyp in HYPS:
    p = HYP_DIR / f"{hyp['id']}.json"
    p.write_text(json.dumps(hyp, indent=2), encoding="utf-8")
    print(f"Wrote {p.name}")
print(f"\nTotal: {len(HYPS)} Brady hypotheses")
